version: '3'

services:
  api-desafio:
    build:
      context: ./api-desafio
      dockerfile: Dockerfile
    command: sh -c ". ./start.sh"
    volumes:
      - ./api-desafio:/api
    ports:
      - "8000:8000"

  front-desafio:
    build:
      context: ./front-desafio
      dockerfile: Dockerfile