version: '3.7'

services:
  api-desafio:
    container_name: api_desafio
    build: "./api-desafio"
    command: sh -c ". ./start.sh"
    volumes:
      - ./api-desafio:/api
    ports:
      - "8000:8000"

  front-desafio:
    container_name: front_desafio
    build: "./front-desafio"
    ports:
      - "8080:8080"